Add ITK-VTK-Viewer example
InsightSoftwareConsortium/itk-viewer-transfer-function-editor pull request #9
Opened 2022-03-31 16:33 UTC by PaulHax

closes #3 
closes #7

2022-03-31 17:02 UTC, thewtex commented on examples/itk-vtk-viewer/index.html
> +      src="https://unpkg.com/itk-vtk-viewer@11.11.2/dist/itkVtkViewerCDN.js"
With a recent update, 11,12.1, there is a major update to the latest vtk.js, itk-wasm, and support for `unpkg.com` -> `jsdelivr.com/npm` (faster and more reliable).

2022-03-31 18:10 UTC, PaulHax commented on examples/itk-vtk-viewer/index.html
> +      src="https://unpkg.com/itk-vtk-viewer@11.11.2/dist/itkVtkViewerCDN.js"
Upgraded. It does feel faster!

2022-03-31 21:35 UTC, thewtex commented on examples/itk-vtk-viewer/index.html
> +      src="https://unpkg.com/itk-vtk-viewer@11.11.2/dist/itkVtkViewerCDN.js"
:+1:

2022-03-31 21:42 UTC, thewtex requested changes
Getting there:

![image](https://user-images.githubusercontent.com/25432/161153234-d9f370f6-f931-4d62-8e06-e6872405830c.png)


In local testing, noticed:

- The itk-vtk-viewer example is not using this transfer function editor. This is a priority.
- The vtk-js example needs `npm i --save-dev vite`
- `npm t` results in:

```
stderr | unknown test
[Vitest] takeCoverage is not available in this NodeJs version.
Coverage could be incomplete. Update to NodeJs 14.18.

stderr | unknown test
[Vitest] takeCoverage is not available in this NodeJs version.
Coverage could be incomplete. Update to NodeJs 14.18.
```

Add .nvmrc with v16?

-

```
❯ npm run test:ui                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                          
> itk-viewer-transfer-function-editor@0.0.1 test:ui /home/matt/src/itk-viewer-transfer-function-editor                                                                                                                                                                                                                                                                                                                                    
> vitest --ui                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                          
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯                                                                                                                                                                                                                      
Error: The following dependencies are imported but could not be resolved:                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                          
  itk-viewer-reference-ui/src/referenceUIMachineOptions.js (imported by /home/matt/src/itk-viewer-transfer-function-editor/examples/itk-vtk-viewer/main.js)                                                                                                                                                                                                                                                                               
  @kitware/vtk.js/favicon (imported by /home/matt/src/itk-viewer-transfer-function-editor/examples/vtk-js/VolumeMapperExample.js)                                                                                                                                                                                                                                                                                                         
  @kitware/vtk.js/macros (imported by /home/matt/src/itk-viewer-transfer-function-editor/examples/itk-vtk-viewer/main.js)                                                                                                                                                                                                                                                                                                                 
  @kitware/vtk.js/Rendering/Profiles/Volume (imported by /home/matt/src/itk-viewer-transfer-function-editor/examples/vtk-js/VolumeMapperExample.js)                                                                                                                                                                                                                                                                                       
  @kitware/vtk.js/Rendering/Core/ColorTransferFunction (imported by /home/matt/src/itk-viewer-transfer-function-editor/examples/vtk-js/VolumeMapperExample.js)                                                                                                                                                                                                                                                                            
  @kitware/vtk.js/Rendering/Misc/FullScreenRenderWindow (imported by /home/matt/src/itk-viewer-transfer-function-editor/examples/vtk-js/VolumeMapperExample.js)                                                                                                                                                                                                                                                                           
  @kitware/vtk.js/IO/Core/HttpDataSetReader (imported by /home/matt/src/itk-viewer-transfer-function-editor/examples/vtk-js/VolumeMapperExample.js)                                                                                                                                                                                                                                                                                       
  @kitware/vtk.js/Common/DataModel/PiecewiseFunction (imported by /home/matt/src/itk-viewer-transfer-function-editor/examples/vtk-js/VolumeMapperExample.js)                                                                                                                                                                                                                                                                              
  @kitware/vtk.js/Rendering/Core/Volume (imported by /home/matt/src/itk-viewer-transfer-function-edito [...]

2022-03-31 23:05 UTC, PaulHax commented
Thanks for the thorough tire kick.  Addressed the issues, except:

> The itk-vtk-viewer example is not using this transfer function editor. This is a priority.

The editor is hard to see.  I added a border.  Is that what you mean?

2022-04-01 01:45 UTC, thewtex commented
> . Addressed the issues,

Thank you!

> The editor is hard to see. I added a border. Is that what you mean?

Yes, I did not see it. Can it replace the existing vtkItkPiecewiseGaussianWidget instead of being placed below?

2022-05-04 19:39 UTC, PaulHax commented
@thewtex The vtkItkPiecewiseGaussianWidget has been completely removed from the itk-vtk-viewer example.

2022-05-05 01:03 UTC, thewtex approved these changes
@PaulHax awesome!!!

A few minor issues noted inline and good to merge!

2022-05-05 01:03 UTC, thewtex commented on examples/basic/main.ts
> +  console.log('Control points', editor.getPoints())
debug code

2022-05-05 01:03 UTC, thewtex commented on README.md
> +npm ci
needs a package-lock.json\

2022-05-05 13:11 UTC, PaulHax commented on README.md
> +npm ci
Updated.

2022-05-05 14:57 UTC, merged